import Providers from '@/Redax/provider';
import './css/main.min.css';
import Header from './components/Header/Header';
/*import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
 */
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="ru">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
